### ISSUE TITLE
用了不到10分钟，后端的服务出问题了

### ISSUE THREAD

**Issue by yayaw** [CloudmindsRobot/dagger#11]
详细日志：
2021-01-13T04:12:09Z [INFO] "GET /api/v1/loki/snapshot?page=1&page_size=10 HTTP/1.0 200 952.044µs "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:12:12Z [INFO] "GET /api/v1/loki/history?page=1&page_size=10 HTTP/1.0 200 863.445µs "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:12:14Z [INFO] "GET /api/v1/loki/labels HTTP/1.0 200 41.342206ms "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:12:14Z [INFO] "GET /api/v1/loki/labels?start=1610510833000000000&end=1610511133000000000 HTTP/1.0 200 42.362902ms "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:12:24Z [INFO] "GET /swagger/index.html HTTP/1.0 200 163.233µs "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:12:24Z [INFO] "GET /swagger/doc.json HTTP/1.0 200 1.197638ms "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
2021-01-13T04:13:05.449Z        [ERROR] controllers/query.go:555        send message to viewer error, write tcp 172.27.0.2:8000->172.27.0.3:60410: write: broken pipe
dagger/backend/controllers.LokiTail
        /go/src/dagger/backend/controllers/query.go:555
github.com/gin-gonic/gin.(*Context).Next
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.RecoveryWithWriter.func1
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83
github.com/gin-gonic/gin.(*Context).Next
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241
github.com/gin-gonic/gin.(*Context).Next
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-contrib/sessions.Sessions.func1
        /go/pkg/mod/github.com/gin-contrib/sessions@v0.0.3/sessions.go:52
github.com/gin-gonic/gin.(*Context).Next
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1890
2021-01-13T04:13:05Z [INFO] "GET /ws/tail?namespace_service=a-prd-whzb/omni-adapter&start=1610511022000000000&level=&pod=&filters= HTTP/1.1 200 2m41.627422872s "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" "
panic: send on closed channel

goroutine 805 [running]:
dagger/backend/utils.WebSocketServerHandler(0xc0001f3ce0, 0xc0003c0c00, 0xc0003c0c60)
        /go/src/dagger/backend/utils/lokiwebsocket.go:97 +0x16c
created by dagger/backend/controllers.LokiTail
        /go/src/dagger/backend/controllers/query.go:547 +0xc5b

**Comment by chenshunliang** [comment]
请更新最新版镜像
